from selenium.webdriver.common.by import By


light_color = (By.ID, 'admin_color_light')
modern_color = (By.ID, 'admin_color_modern')
evergreen_color = (By.ID, 'admin_color_bbp-evergreen')
mint_color = (By.ID, 'admin_color_bbp-mint')
blue_color = (By.ID, 'admin_color_blue')
coffee_color = (By.ID, 'admin_color_coffee')
ectoplasm_color = (By.ID, 'admin_color_ectoplasm')
midnight_color = (By.ID, 'admin_color_midnight')
ocean_color = (By.ID, 'admin_color_ocean')
sunrise_color = (By.ID, 'admin_color_sunrise')
nickname = (By.ID, 'nickname')
first_name = (By.ID, 'first_name')
last_name = (By.ID, 'last_name')
email_name = (By.ID, 'email')
website_profile = (By.ID, 'url')
biographical_info = (By.ID, 'description')
new_password_name = (By.ID, 'new_application_password_name')
do_new_password = (By.ID, 'do_new_application_password')
update_profile = (By.ID, 'submit')
